version: "3.2"
services:

  docker-academy-backend:
    container_name: docker-academy-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 9.9.9.9
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8000 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: ["./bin/api"]
