version: "3.2"
services:

  docker-academy-frontend:
    container_name: docker-academy-frontend
    build:
      context: ./Frontend
      dockerfile: Frontend/Dockerfile
    ports:
      - "80:80"
    dns:
      - 8.8.8.8
      - 9.9.9.9
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: on-failure
    depends_on:
      - "docker-academy-backend"
