version: "3.2"
services:

  docker-academy-backend:
    container_name: docker-academy-backend
    build: .
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 9.9.9.9
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: on-failure
    command: ["./bin/api"]
